[package]
name = "midgar"
version = "0.1.0"
authors = ["Gabriel Martinez <reitaka@gmail.com>"]

[dependencies]
cgmath = "0.16"
glium = { version = "0.18", features = [], default-features = false }
glium_sdl2 = "0.15"
glyph_brush = "0.2"
image = "0.20"
maybe-owned = "0.3"
moving-average = { git = "https://github.com/mystal/moving-average" }
# rand = "0.3"
sdl2 = "0.30"
