[package]
name = "midgar"
version = "0.1.0"
authors = ["Gabriel Martinez <reitaka@gmail.com>"]

[dependencies]
cgmath = "^0.12.0"
glium = { version = "^0.14.0", features = [], default-features = false }
glium_sdl2 = "^0.12.0"
image = "^0.10.3"
# rand = "^0.3.0"
sdl2 = "^0.19.0"
